### ISSUE TITLE
about validation on nuscenes

### ISSUE THREAD

**Issue by Terminal-K** [PRBonn/MapMOS#17]
Hi, benemer!
I would like to know how to use the nuscenes dataset for validation because I'm not familiar with it. How should I set up the "sequence" parameter?
https://github.com/PRBonn/MapMOS/blob/56b2cc857d909f97f1a7fd7b582c3817512e1eb1/src/mapmos/datasets/nuscenes.py#L33-L34
Looking forward to your response :)

**Comment by benemer** [comment]
The sequence parameter refers to the sequence ID in nuscenes. For example, for sequence `scene-0271`, you have to pass the sequence ID `271`. You can find the IDs for the validation set [here](https://github.com/nutonomy/nuscenes-devkit/blob/master/python-sdk/nuscenes/utils/splits.py) or get it via Python:

```python
from nuscenes.utils.splits import val
sequences = [v.split("-")[1] for v in val]
```

Note that you have to modify [these](https://github.com/PRBonn/MapMOS/blob/56b2cc857d909f97f1a7fd7b582c3817512e1eb1/src/mapmos/datasets/nuscenes.py#L45) lines in the Nuscenes data loader to load the correct database. Be aware that calling the NuScenes function in the data loader takes some time for the "v1.0-trainval" data and you have to do it for each sequence of the validation set. To mitigate this, you can modify the pipeline to iterate over all sequences and modify the data loader to create the NuScenes object once on import:

```python
[..]
import nuscenes
from nuscenes.nuscenes import NuScenes

__nusc_dataroot__ = "/path/to/nuScenes"
__nusc_version__: str = "v1.0-trainval"
 __nusc__ = NuScenes(dataroot=__nusc_dataroot__, version=__nusc_version__)

class MOSNuscenesDataset(NuScenesDataset):
[...]
```

And then you set ``self.nusc = __nusc__`` in the `__init__`.

**Comment by Terminal-K** [comment]
Many thanks!! You really help me a lot!
