### ISSUE TITLE
'Odometry' object has no attribute 'poses'

### ISSUE THREAD

**Issue by Skrsch** [PRBonn/MapMOS#19]
Thank you for this open-source work!
After following the instructions from the readme, installation of the project worked smoothly.
However, when running with data, I get the following error:
'Odometry' object has no attribute 'poses'
If I manually initialize poses, I get 'Odometry' object has no attribute 'get_adaptive_threshold'.
I assume this is linked  to the imported kiss_icp.
I have installed kiss_icp in version 0.4.0.

Help is very appreciated and I am happy if I can support your effort!

**Comment by benemer** [comment]
You most likely have installed `kiss-icp` from the current main branch (which will still show version 0.4.0), but is missing the `self.poses` attribute [here](https://github.com/PRBonn/kiss-icp/blob/c6224a1de53e1fa864daa976d52032ff1cb397c1/python/kiss_icp/kiss_icp.py#L36).

There are two easy ways to fix that:

1. You uninstall `kiss-icp` and install the released version 0.4.0 (either via `pip install kiss-icp` or by checking out at the release tag on Github).

OR

2. You checkout `MapMOS` at `benedikt/migrate_kiss`. This one reflects the latest `kiss-icp` changes and will be merged into main as soon as we make a new `kiss-icp` release.

Let me know if that worked :)

**Comment by benemer** [comment]
We just release a new version of `kiss-icp` and `MapMOS`, make sure to update both and everything should work :+1:
