### ISSUE TITLE
Apollo and KITTI tracking benchmarking

### ISSUE THREAD

**Issue by vb44** [PRBonn/MapMOS#26]
Hi,

I am benchmarking some results on the Apollo and KITTI tracking datasets linked on this page. I just wanted to confirm the performance IoU is evaluated using the [semantic-kitti-api](https://github.com/PRBonn/semantic-kitti-api)? I.e., generate the labels using the desired MOS algorithm with full-range scans and use *evaluate_mos.py* directly.

Thank you for sharing these datasets!

Best regards,
Vedant

**Comment by benemer** [comment]
Are you talking about your own results or the results obtained by using MapMOS? When running our pipeline, you will get a report with the same metrics, just make sure to run it on the full range via the config

```yaml
mos:
  max_range_mos: -1.0 # No limit
```

If you want to evaluate your own generated `.label` results, you can proceed as you described!

**Comment by vb44** [comment]
Thank you for the prompt response!
