### ISSUE TITLE
Question regarding Generalization benchmark

### ISSUE THREAD

**Issue by JulesSanchez** [PRBonn/MapMOS#4]
Thanks for the fantastic and exhaustive work.
In Table II, are the results proposed with a model trained on the train split (00->07, 09, 10) or on the trainval split (00->10) as it is often used for benchmark submissions ?

Best,

Jules

**Comment by benemer** [comment]
Hey, thanks for the feedback!

Please check Sec. IV. A. of our [paper](https://www.ipb.uni-bonn.de/wp-content/papercite-data/pdf/mersch2023ral.pdf):

```
A. Datasets, Metrics, and Baselines

For the following experiments, we train all models on
the moving labels of the SemanticKITTI [3], [4] training
sequences 00-07 and 09-10 and use sequence 08 for validation.
```
