### ISSUE TITLE
How to use the labelled apollo dataset for mos?

### ISSUE THREAD

**Issue by beyounged** [PRBonn/MapMOS#6]
Hello dear author, recently I was planning to use the apollo dataset you released specifically for MOS, I downloaded the dataset directly, but I get an error when I use the dataset directly on the MotionSeg3D, how to use the dataset correctly?

**Comment by benemer** [comment]
Hi, I closed this issue because it is not related to MapMOS. Please contact the authors of MotionSeg3D for instructions on how to run their code. As mentioned in the acknowledgements, the MotionSeg3D results have been provided by the original authors.

Best
Benedikt
