### ISSUE TITLE
Problems with pydantic?

### ISSUE THREAD

**Issue by DeepDuke** [PRBonn/MapMOS#9]
May I ask the dependencies for pydantic? I met several problems from `pydantic`  
```
File "/home/spacex/miniconda3/envs/LiDAR-MOS/lib/python3.7/site-packages/pydantic/main.py", line 719, in __setattr__
    if self.__pydantic_private__ is None or name not in self.__private_attributes__:
  File "/home/spacex/miniconda3/envs/LiDAR-MOS/lib/python3.7/site-packages/pydantic/main.py", line 699, in __getattr__
    pydantic_extra = object.__getattribute__(self, '__pydantic_extra__')
AttributeError: __pydantic_extra__
```

**Comment by benemer** [comment]
The latest release of KISS requires pydantic>2, which does not work with our code currently. I will update it soon.

You can for now install kiss-icp<0.3.0, this should still work.

**Comment by benemer** [comment]
Can you please try to see if it works on [this](https://github.com/PRBonn/MapMOS/tree/upgrade_kiss_icp) branch?

**Comment by DeepDuke** [comment]
I will have a  try

**Comment by benemer** [comment]
I will close this issue, please re-open if it did not help
